<!--
 * @Descripttion: 
 * @Author: zlj
 * @Date: 2020-06-15 14:21:10
--> 

# reuqsets超时重试

连不上服务器会出现异常：requests.exceptions.ConnectionError

## timeout 

可以加个 timeout 超时时间，达到这个请求超时时间就结束,如 15 秒超时
```.bash
import requests

s = requests.session()

url = "https://www.github.com/"
r = s.request("GET", url=url, timeout=15)
print(r.text)
```

## 失败重试 max_retries

```.hash
import requests
from requests.adapters import HTTPAdapter
s = requests.session()



# max_retries=3 重试3次
s.mount('http://', HTTPAdapter(max_retries=3))
s.mount('https://', HTTPAdapter(max_retries=3))


url = "https://www.github.com/"
r = s.request("GET", url=url, timeout=15)
print(r.text)
这样每次请求超时15s，超时后会重试3次，最大请求时长45s.
```

## 跳过执行测试用例

```.bash
 @unittest.skip(reason) ：跳过测试用例，reason  为测试被跳过的原因
 @unittest.skipIf(condition, reason) ：当 condition 为真时，跳过测试用例。
 @unittest.skipUnless(condition, reason) ：跳过测试用例，除非 condition 为真
 @unittest.expectedFailure ：把测试用例标记为预计失败；如果测试不通过，会被认为测试成功；如果测试通过了，则被认为是测试失败
```

